### ISSUE TITLE
Illegal hardware instruction when trying to attach message

### ISSUE THREAD

**Issue by ZhongXiLu** [mhzawadi/homebrew-cbonsai#3]
I get following error when I try to run `cbonsai -m "Test"`:
```bash
[1]    25154 illegal hardware instruction  cbonsai -m "Test"
```
Everything else work fine though.

---

macOS 11.5.2 (Intel)
Homebrew 3.2.10-64-gfd46a17
cbonsai 1.3.2

**Comment by mhzawadi** [comment]
Hello 👋🏼

**Comment by mhzawadi** [comment]
Hello 👋🏼 
must have missed this, that is odd. have seen that homebrew has moved the location of stuff, so will be updating this repo to fix that. 

Could you try pulling from the [upstream repo](https://gitlab.com/jallbrit/cbonsai/-/tree/master)?

**Comment by ZhongXiLu** [comment]
I had some problems installing cbonsai from scratch. That's why I relied on this Homebrew formula instead.
Anyway, it's not that urgent though. 😛

**Comment by mhzawadi** [comment]
ok, it works if you make from this repo (have fixed the issue). But I cant workout why brew doesnt work.

let me know if that helps

**Comment by ZhongXiLu** [comment]
Yeah, I have issues with making it myself, even with this repo, but again, it's not that big of a deal.
Thanks anyway for your help.

**Comment by mhzawadi** [comment]
no problem, will close this for now.
