### ISSUE TITLE
Adding the formula to Homebrew

### ISSUE THREAD

**Issue by osalbahr** [mhzawadi/homebrew-cbonsai#6]
I was a bit disappointed when I couldn't (directly) `brew install cbonsai`. Ofc, there is tapping or installing with the full name works. But would you be interested in adding it as an official formula in Homebrew? I'm not sure what the requirements are.

**Comment by mhzawadi** [comment]
Hi @osalbahr 

I have a [PR](https://github.com/Homebrew/homebrew-core/pull/130784) in to do just that, lets see how I get on

**Comment by mhzawadi** [comment]
so thats a no then

```
From our [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff) documentation:

We frown on authors submitting their own work unless it is very popular.

Based off the GitHub statistics, this does not meet this criteria. It also does not meet our notability requirements:

<30 forks, <30 watchers and <75 stars
```

**Comment by osalbahr** [comment]
I think there’s a misunderstanding. Homebrew thought that you’re the owner of cbonsai. The gitlab repo https://gitlab.com/jallbrit/cbonsai has over 75 stars (almost 300). Did you include the original gitlab in your request?

**Comment by osalbahr** [comment]
I’d be happy to help with creating a new formula that uses the gitlab link instead of the GitHub link. Let me know if you face any issues. I’m new to formulae but I’ll look into it.

**Comment by osalbahr** [comment]
You could maybe use https://github.com/macports/macports-ports/blob/master/games/cbonsai/Portfile as reference

**Comment by osalbahr** [comment]
Hi, are you interested in porting cbonsai.rb to use the gitlab link instead?

Edit: I see you already tried to do that. Is there anything I can help with?
